<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2VJ4R1V" ignored="0" name="Test" tests="7" failures="1" timestamp="2021-11-28T12:38:48 IST" time="0.108" errors="0">
  <testcase name="password_Validation" time="0.016" classname="com.Test_Driven_Devlopment.Failed_Test"/>
  <testcase name="username_Validation" time="0.0" classname="com.Test_Driven_Devlopment.Failed_Test">
    <skipped/>
  </testcase> <!-- username_Validation -->
  <testcase name="username_Validation" time="0.0" classname="com.Test_Driven_Devlopment.Failed_Test">
    <skipped/>
  </testcase> <!-- username_Validation -->
  <testcase name="username_Validation" time="0.0" classname="com.Test_Driven_Devlopment.Failed_Test">
    <skipped/>
  </testcase> <!-- username_Validation -->
  <testcase name="username_Validation" time="0.0" classname="com.Test_Driven_Devlopment.Failed_Test">
    <skipped/>
  </testcase> <!-- username_Validation -->
  <testcase name="username_Validation" time="0.0" classname="com.Test_Driven_Devlopment.Failed_Test">
    <skipped/>
  </testcase> <!-- username_Validation -->
  <testcase name="username_Validation" time="0.0" classname="com.Test_Driven_Devlopment.Failed_Test">
    <failure type="java.lang.AssertionError" message="expected [Deepak] but found [Deeparajan]">
      <![CDATA[java.lang.AssertionError: expected [Deepak] but found [Deeparajan]
at com.Test_Driven_Devlopment.Failed_Test.username_Validation(Failed_Test.java:11)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- username_Validation -->
</testsuite> <!-- Test -->
